config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
  post 'post/create'
  post 'post/like'
  post 'post/comment'
  get 'user/index'
  get 'user/:id', to: 'user#profile', as: 'user_profile'
  post 'user/avatar'
  post 'user/follow'
  post 'user/unfollow'
  post 'user/username'
  post 'post/repost'
  get 'community/index'
  post 'community/create'
  post 'community/join'
  post 'community/leave'
  get 'community/:id', to: 'community#community', as: 'community_show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/community.rb
class Community < ApplicationRecord
  has_one_attached :image
  has_many :community_users
  has_many :users,  through: :community_users
  has_many :posts
end

app/models/community_user.rb
class CommunityUser < ApplicationRecord
  belongs_to :user
  belongs_to :community
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :likes
  has_many :comments
  has_many :reposts
  belongs_to :community
end

app/models/relationship.rb
class Relationship < ApplicationRecord
end

app/models/repost.rb
class Repost < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_many :posts
  has_one_attached :avatar
  has_many :relationships, foreign_key: :followed_id
  has_many :reposts
  has_many :following, class_name: 'Relationship', foreign_key: :follower_id
  has_many :followers, class_name: 'Relationship', foreign_key: :followed_id
  has_many :community_users
  has_many :communities, through: :community_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  private
  def authenticate_user!
    redirect_to new_user_session_path unless current_user
  end
end

app/controllers/concerns/community_controller.rb
class CommunityController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @communities = Community.all().reverse
  end

  def community
    @user = User.find(current_user.id)
    @community = Community.find(params[:id])
  end
  def create
    community = Community.create(name: params[:name])
    if community.save
      community.image.attach(params[:image])
      redirect_to request.referrer, notice: t('community_created_successfully'), allow_other_host: true
    end
  end

  def join
    CommunityUser.create(user_id: current_user.id, community_id: params[:community_id])
    redirect_to request.referrer, notice: t('joined_community_successfully'), allow_other_host: true
  end

  def leave
    CommunityUser.where(user_id: current_user.id, community_id: params[:community_id]).destroy_all
    redirect_to request.referrer, notice: t('left_community_successfully'), allow_other_host: true
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  def index
    @feeds = []
    if current_user
      user = User.find(current_user.id)
      user_following = user.following.map { |f| f.followed_id }
      posts = Post.where(user_id: user_following, community_id: nil)
      comments = Comment.where(user_id: user_following)
      reposts = Repost.where(user_id: user_following)
      community_posts = Post.where(community_id: user.community_users.map { |cu| cu.community_id })
      all_activities = posts + comments + reposts + community_posts
      @feeds = all_activities.sort_by(&:created_at).reverse[(Integer(params[:page] || 1) * 10) - 10, 10] || []
      @pages_count = (all_activities.length() / 10.to_f).ceil
    end
  end
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def create
    post = Post.create(user_id: current_user.id, post_text: params[:post_text], has_image: false, community_id: params[:community_id])
    if post.save
      post.image.attach(params[:image]) if params[:image].present?
      post.update(has_image: true) if params[:image].present?
      redirect_to request.referrer, notice: "تم إنشاء المنشور بنجاح.", allow_other_host: true
    end
  end
  def like
    Like.create(user_id: current_user.id, post_id: params[:post_id])
    redirect_to request.referrer, notice: "تم الإعجاب بنجاح.", allow_other_host: true
  end
  def comment
    Comment.create(user_id: current_user.id, post_id: params[:post_id], comment_text: params[:comment_text])
    redirect_to request.referrer, notice: "تم إضافة التعليق بنجاح.", allow_other_host: true
  end
  def repost
    Repost.create(user_id: current_user.id, post_id: params[:post_id])
    redirect_to request.referrer, notice: "تم إعادة نشر المنشور بنجاح.", allow_other_host: true
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.where.not(id: current_user.id)
  end

  def profile
    user = User.find(params[:id])
    posts = user.posts
    reposts = user.reposts
    all_activities = posts + reposts
    @feeds = all_activities.sort_by(&:created_at).reverse
    @user = user
  end

  def avatar
    user = User.find(current_user.id)
    user.avatar.attach(params[:avatar])
    redirect_to request.referrer, notice: 'تم تحديث صورة الملف الشخصي بنجاح.', allow_other_host: true
  end

  def follow
    Relationship.create(follower_id: current_user.id, followed_id: params[:followed_id])
    redirect_to request.referrer, notice: 'تابعت المستخدم بنجاح.', allow_other_host: true
  end

  def unfollow
    Relationship.find_by(follower_id: current_user.id, followed_id: params[:followed_id]).destroy
    redirect_to request.referrer, notice: 'ألغيت متابعة المستخدم بنجاح.', allow_other_host: true
  end

  def username
    user = User.find(current_user.id)
    user.update(username: params[:username])
    redirect_to request.referrer, notice: 'تم تحديث اسم المستخدم بنجاح.', allow_other_host: true
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/community/community.html.erb
<h4 class="text-3xl font-bold"><%= @community.name %></h4>
<h2 class="text-xl mb-4"><%= t('members') %>: <%= @community.users.count %> </h2>
<div class="row">
  <div class="col col-md-8">
    <% if @user.communities.select {|c| c.id == @community.id }.count > 0 %>
      <%= render 'shared/create_post', community_id: @community.id %>
      <% @community.posts.each do |post| %>
        <div class="mx-auto my-5 max-w-sm bg-white border border-gray-200 rounded-lg shadow-sm dark:bg-gray-800 dark:border-gray-700">
          <%= render 'shared/post_card', post: post, type: "post" %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="col col-md-4">
    <% @community.users.each do |user| %>
        <div class="p-2 mx-auto my-5 max-w-sm bg-white border border-gray-200 rounded-lg shadow-sm dark:bg-gray-800 dark:border-gray-700">
          <div class="flex items-center">
              <% if user.avatar.attached? %>
                  <img src="<%= url_for(user.avatar) %>" class="w-10 h-10 rounded-full inline-block mr-2" />
                  <h3 class="inline-block"><a href="/user/<%= user.id %>"><%= user.username %></a></h3>
              <% else %>
                  <div class="w-10 h-10 rounded-full bg-gray-300 inline-block mr-2"></div>
              <% end %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/community/index.html.erb
<div class="container mx-auto p-4">
    <div class="p-6 mx-auto my-5 max-w-sm bg-white border border-gray-200 rounded-lg shadow-sm dark:bg-gray-800 dark:border-gray-700">
        <form enctype="multipart/form-data"  class="space-y-4" action="/community/create" method="post">
            <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= t('create_new_community') %></h5>
            <input class="border border-gray-300 rounded-lg p-2 w-full mb-2" type="text" name="name" placeholder="<%= t('community_name') %>">
            <input class="border border-gray-300 rounded-lg p-2 w-full mb-2" type="file" name="image"%>
            <button class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800"
            type="submit"><%= t('create_community') %></button>
        </form>
    </div>
</div>

<div class="grid grid-cols-4 gap-4">
        <% @communities.each do |community| %>
            <div class="col-span-4 sm:col-span-2 md:col-span-1 lg:col-span-1 p-4">
                <div class="p-6 mx-auto my-5 max-w-sm bg-white border border-gray-200 rounded-lg shadow-sm dark:bg-gray-800 dark:border-gray-700">
                    <% if community.image.attached? %>
                        <img src="<%= url_for(community.image) %>" class="rounded-lg mb-4" />
                    <% end %>
                    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><a href="#"><a href="/community/<%= community.id %>"><%= community.name %></a></h5>
                    <% if @user.communities.select {|c| c.id == community.id }.count == 0 %>
                            <form action="/community/join" method="post">
                                <input type="hidden" name="community_id" value="<%= community.id %>">
                                <button type="submit" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800"><%= t('join_community') %></button>
                            </form>
                    <% else %>
                            <form action="/community/leave" method="post">
                                <input type="hidden" name="community_id" value="<%= community.id %>">
                                <button type="submit" class="text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 focus:outline-none dark:focus:ring-red-800"><%= t('leave_community') %></button>
                            </form>
                    <% end %>
                </div>
            </div>
        <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  dir="rtl" lang="ar">
  <head>
    <title><%= content_for(:title) || "Social Media Network 2025" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>


<nav class="bg-white border-gray-200 dark:bg-gray-900">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
  <a href="#" class="flex items-center space-x-3 rtl:space-x-reverse">
      <img href="/" src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Flowbite Logo" />
      <span href="/" class="self-center text-1xl font-semibold whitespace-nowrap dark:text-white">مشروع شبكة تواصل اجتماعي</span>
  </a>
  <div class="flex items-center md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
      <button type="button" class="flex text-sm bg-gray-800 rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
        <span class="sr-only">Open user menu</span>
      <% if user_signed_in? %>
          <img class="w-8 h-8 rounded-full" src="<%= url_for(current_user.avatar) if current_user.avatar.attached? %>" alt="user photo">
      <% end %>
      </button>
      <!-- Dropdown menu -->
      <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow-sm dark:bg-gray-700 dark:divide-gray-600" id="user-dropdown">
        <div class="px-4 py-3">
          <span class="block text-sm text-gray-900 dark:text-white">Bonnie Green</span>
          <span class="block text-sm  text-gray-500 truncate dark:text-gray-400">name@flowbite.com</span>
        </div>
        <ul class="py-2" aria-labelledby="user-menu-button">
          <li>
            <%= button_to "تسجيل الدخول", new_user_session_path, method: :post, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" %> |
            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Dashboard</a>

          </li>
          <li>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Settings</a>
          </li>
          <li>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Earnings</a>
          </li>
          <li>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Sign out</a>
          </li>
        </ul>
      </div>
      <button data-collapse-toggle="navbar-user" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-user" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
        </svg>
    </button>
  </div>
  <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-user">
    <ul class="flex flex-col font-medium mx-2 p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
      <li>
      <%= link_to "الصفحة الرئيسية", class: "block py-2 px-3 text-white bg-blue-700 rounded-sm md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500"%>
      </li>
      <br>
      <hr>
      <% if user_signed_in? %>
      <hr>
        <li>
        <a href="<%= community_index_path %>" class="block py-2 px-3 text-gray-900 rounded-sm hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"><%= t('view_communities') %></a>
      </li>
      <li>
        <a href="<%= user_profile_path(current_user.id) %>" class="block py-2 px-3 text-gray-900 rounded-sm hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"><%= t('my_Profile') %></a>
      </li>
      <hr>
      <li>
        <%= button_to "تسجيل خروج", destroy_user_session_path, method: :delete, class: "block py-2 px-3 text-gray-900 rounded-sm hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %>
      </li>
      <% else %>
      <li>
        <%= button_to "تسجيل الدخول", new_user_session_path, method: :post, class: "block py-2 px-3 text-gray-900 rounded-sm hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %>
      </li>
      <% end %>
    </ul>
  </div>
  </div>
</nav>
    <div class="m-4">
      <hr>
      <% if user_signed_in? %>
        مرحبًا، <%= current_user.username %>!
      <% else %>
        مرحبًا، زائر!
      <% end %>
      <div class="my-5">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
    </div>
    <div class="container mx-auto mt-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_post_card.html.erb
<div class="flex items-center space-x-4 mb-4 p-4">
    <% if post.user.avatar.attached? %>
        <img class="w-10 h-10 rounded-full" src="<%= url_for(post.user.avatar) %>" alt="User avatar" />
    <% end %>
    <a class="font-medium text-gray-900 dark:text-white inline-block align-top"  href="<%= user_profile_path(post.user.id) %>"><%= post.user.username %></a>
    <a class="font-medium text-gray-900 dark:text-white">
        <% if (Time.now() - post.created_at).ceil < 60 %>
            <small class="text-gray-500"> <%= (Time.now() - post.created_at).ceil %> <%= t('seconds_ago') %> </small>
        <% elsif ((Time.now() - post.created_at).ceil / 60) < 60 %>
            <small class="text-gray-500"> <%= ((Time.now() - post.created_at).ceil / 60) %> <%= t('minutes_ago') %> </small>
        <% elsif ((Time.now() - post.created_at).ceil / 3600) < 24 %>
            <small class="text-gray-500"> <%= ((Time.now() - post.created_at).ceil / 3600) %> <%= t('hours_ago') %> </small>
        <% elsif ((Time.now() - post.created_at).ceil / 86400) < 30 %>
            <small class="text-gray-500"> <%= ((Time.now() - post.created_at).ceil / 86400) %> <%= t('days_ago') %> </small>
        <% elsif ((Time.now() - post.created_at).ceil / 2592000) > 12 %>
            <small class="text-gray-500"> <%= ((Time.now() - post.created_at).ceil / 2592000) %> <%= t('months_ago') %> </small>
        <% else %>
            <small class="text-gray-500"> <%= ((Time.now() - post.created_at).ceil / 31536000) %> <%= t('years_ago') %> </small>
        <% end %>
    </a>
</div>
<% if post.image.attached? %>
    <a href="#">
    <img class="rounded-t-lg" src="<%= url_for(post.image) %>" alt="" />
    </a>
<% end %>
<div class="p-5 ">
    <p class="font-normal text-gray-700 dark:text-gray-400"><%= post.user.id %></p>
    <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"><%= post.post_text %></p>
    <p class="mt-3 text-sm text-gray-500 dark:text-gray-400">Posted by: <%= post.user.email %> at <%= post.created_at %></p>
    <br/>
<div class="flex space-x-2">
    <form action="/post/like" method="post">
        <input type="hidden" name="post_id" value="<%= post.id %>">
        <% if post.likes.select { |like| like.user_id == current_user.id }.count == 0 %>
            <button type="submit" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
            >👍</button>
        <% else %>
            <button disabled class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-gray-600 rounded-lg hover:bg-gray-500 focus:ring-4 focus:outline-none focus:ring-gray-400 dark:bg-gray-400 dark:hover:bg-gray-500 dark:focus:ring-gray-500"
            >👍</button>
        <% end %>
    </form>
    <button onclick="toggleAccordion(<%= post.id %>)" class=" inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        <span>💬</span>
    </button>
    <form action="/post/repost" method="post">
        <input type="hidden" name="post_id" value="<%= post.id %>">
    <% if post.reposts.select { |repost| repost.user_id == current_user.id }.count == 0 %>
        <button type="submit" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
        >🔂 </button>
    <% else %>
        <button disabled class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-gray-600 rounded-lg hover:bg-gray-500 focus:ring-4 focus:outline-none focus:ring-gray-400 dark:bg-gray-400 dark:hover:bg-gray-500 dark:focus:ring-gray-500"
        >🔂 </button>
    <% end %>
    </form>
    </div>
    <div id="content-<%= post.id %>" class="max-h-0 overflow-hidden transition-all duration-300 ease-in-out">
    <form class="mb-2" action="/post/comment" method="post">
        <input type="hidden" name="post_id" value="<%= post.id %>">
        <label for="comment" class="py-2 block mb-2 text-sm font-medium text-gray-900 dark:text-gray-400"><%= t('Add_a_comment') %></label>
        <textarea name="comment_text" type="text" id="comment" class="mb-2 block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="<%= t('Your_comment') %>">
        </textarea>
        <button type="submit" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
        ><%= t('Add_a_comment') %></button>
    </form>
    <% post.comments.each do |comment| %>
        <div class="p-5 mx-auto my-5 max-w-sm bg-white border border-gray-200 rounded-lg shadow-sm dark:bg-gray-800 dark:border-gray-700">
            <% if comment.user.avatar.attached? %>
                <img class="w-10 h-10 rounded-full" src="<%= url_for(comment.user.avatar) %>" alt="User avatar" />
            <% end %>
            <p class="font-normal text-gray-700 dark:text-gray-400"><a href="<%= user_profile_path(comment.user.id) %>"><%= comment.user.username %></a>: <br> <%= comment.comment_text %></p>
        </div>
    <% end %>
    </div>
</div>

app/views/user/index.html.erb
<% @users.each do |user| %>
    <div class="flex user-card justify-between  p-4 mx-auto my-5 max-w-sm bg-white border border-gray-200 rounded-lg shadow-sm dark:bg-gray-800 dark:border-gray-700">
        <h2 class="text-lg font-semibold inline-block"><a href="<%= user_profile_path(user.id) %>"> <%= user.username %></a></h2>
        <br>
        <% if user.followers.select { |relationship| relationship.follower_id == current_user.id}.count > 0 %>
            <form class="inline-block" action="/user/unfollow" method="post">
                <input type="hidden" name="followed_id" value="<%= user.id %>">
                <button type="submit" class="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600"> <%= t('unfollow') %> </button>
            </form>
        <% else %>
            <form action="/user/follow" method="post">
                <input type="hidden" name="followed_id" value="<%= user.id %>">
                <button type="submit" class="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600"> <%= t('follow') %> </button>
            </form>
        <% end %>
    </div>
<% end %>